name: Build Android
on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v4
      - name: Install flutter sdk
        uses: subosito/flutter-action@v2.16.0
        with:
          channel: stable
          cache: true
      - run: flutter --version
      - run: flutter pub get
