on:
  pull_request:
    types:
      - opened
    branches:
      - 'main'
jobs:
  Pull-request-was-created:
    if:  startsWith(github.head_ref, 'releases/')
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo The PR was created
