on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - if: endsWith(github.event.release.tag_name, 'beta')
        uses: JangInHwa/flutter-ci-cd-study/.github/workflows/deploy beta.yml@main
      - if: ! ${{endsWith(github.event.release.tag_name, 'beta')}}
        uses: JangInHwa/flutter-ci-cd-study/.github/workflows/deploy prod.yml@main

