name: Deploy Beta
on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Build ios
        uses: JangInHwa/flutter-ci-cd-study/.github/workflows/build ios.yml@main
