on:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
jobs:
  Pull-request-was-created:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repository...
        uses: actions/checkout@v3
      - name: Get App Version..
        id: yq
        uses: mikefarah/yq@master
        with:
          cmd: yq -r '.version' 'pubspec.yaml'
      - name: Create Github tag and release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.yq.outputs.result }}
          release_name: Release ${{ steps.yq.outputs.result }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

